// ~/~ begin <<docs/architecture/frontend/diff.md#frontend-view-collapse-test>>[init]
import { describe, expect, test } from "bun:test";
import type { FileDiff } from "../api";
import { collapseReason, LARGE_DIFF } from "./collapse";

function modified(path: string, patch: string): FileDiff {
  return {
    status: "modified",
    path,
    binary: false,
    oldBlob: "a",
    newBlob: "b",
    patch,
    structural: { kind: "unavailable", reason: "test" },
  };
}

function added(path: string, lines: string[]): FileDiff {
  return {
    status: "added",
    path,
    binary: false,
    oldBlob: null,
    newBlob: "b",
    structural: { kind: "unavailable", reason: "test" },
    patch: [
      `@@ -0,0 +1,${lines.length} @@`,
      ...lines.map((line) => `+${line}`),
      "",
    ].join("\n"),
  };
}

const SMALL = "@@ -1,2 +1,2 @@\n-old\n+new\n keep\n";

describe("collapseReason", () => {
  test("folds a lock file by its name, wherever it sits", () => {
    expect(collapseReason(modified("bun.lock", SMALL))).toBe("lock file");
    expect(collapseReason(modified("crates/x/Cargo.lock", SMALL))).toBe(
      "lock file",
    );
    expect(collapseReason(modified("tools/some.lock", SMALL))).toBe(
      "lock file",
    );
  });

  test("folds a path only a build step writes", () => {
    expect(collapseReason(modified("dist/app.js", SMALL))).toBe("generated");
    expect(collapseReason(modified("web/app.min.js", SMALL))).toBe("generated");
  });

  test("folds a new file whose top carries a generator's marker", () => {
    // arrange
    const file = added("api/types.go", [
      "// Code generated by protoc-gen-go. DO NOT EDIT.",
      "package api",
    ]);

    // act
    const reason = collapseReason(file);

    // assert
    expect(reason).toBe("generated");
  });

  test("leaves open a file that mentions the marker further down", () => {
    // arrange
    const file = added("src/marker.ts", [
      ...Array.from({ length: 10 }, () => "// ordinary"),
      'const MARKER = "@generated";',
    ]);

    // act
    const reason = collapseReason(file);

    // assert
    expect(reason).toBeNull();
  });

  test("folds a diff with more changed lines than the limit", () => {
    // arrange
    const lines = Array.from({ length: LARGE_DIFF + 1 }, (_, n) => `l${n}`);

    // act
    const reason = collapseReason(added("src/big.ts", lines));

    // assert
    expect(reason).toBe(`large diff, ${LARGE_DIFF + 1} changed lines`);
  });

  test("leaves an ordinary change open", () => {
    expect(collapseReason(modified("src/app.ts", SMALL))).toBeNull();
  });
});
// ~/~ end
